language: java
before_install:
  - wget http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz
  - tar -zxf android-sdk_r20.0.3-linux.tgz
  - export PROJ_HOME=~/builds/questmaster/FATpRemote
  - export TEST_DIR=tests
  - export ANDROID_HOME=${PROJ_HOME}/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
#  - android list sdk --all --extended # can be used to check for filter id's
  - android -s update sdk --filter tool,platform-tool,android-15,sysimg-15 --no-ui --force
  - android -s update project --path ${PROJ_HOME}
  - android -s update test-project --path ${PROJ_HOME}/${TEST_DIR} -m ${PROJ_HOME}
  
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start 
  - echo no | android create avd --force --sdcard 64M --name "defaultAVD" --target android-15 --abi armeabi-v7a
  - emulator -avd defaultAVD -prop persist.sys.language=de -prop persist.sys.country=DE -noaudio -no-boot-anim &
  - sleep 45
  
script: 
  - cd ${TEST_DIR}
  - ant debug
  - ant test